services:
  minecraft:
    image: 'itzg/minecraft-server'
    hostname: minecraft
    container_name: minecraft
    cap_add:
      - "SYS_ADMIN"
    ports:
      - 25565:25565 # Minecraft
      - 25575:25575 # Rcon
      - 8100:8100   # Blue Map
    environment:
      EULA: true
      TYPE: 'FABRIC'
      VERSION: '1.21.4'
      MEMORY: '6G'
      MAX_PLAYERS: 2
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 8
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 200
      PAUSE_WHEN_EMPTY_SECONDS: 60
      DIFFICULTY: 'hard'
      SPAWN_PROTECTION: 0
      ENABLE_RCON: true
      SYNC_CHUNK_WRITES: false
      ENFORCE_SECURE_PROFILE: true
      OVERRIDE_SERVER_PROPERTIES: true
      REMOVE_OLD_VANILLATWEAKS: true
      MOTD: "                             §4§lPeak\n             §7⚔  §oDeath Swap awaits!  §7⚔" # Needs double quotes for '\n' to work
      ICON: 'https://github.com/peaksmp/server/blob/main/config/MiniMOTD/icons/peak.png?raw=true'
      MODS_FILE: '/extras/mods.txt'
      VANILLATWEAKS_FILE: '/extras/datapacks.json,/extras/crafting-tweaks.json'
      JVM_XX_OPTS: '-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:+DisableExplicitGC'
      JVM_DD_OPTS: '-Dfile.encoding=UTF-8'
    volumes:
      - ./minecraft:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./datapacks.json:/extras/datapacks.json:ro
      - ./crafting-tweaks.json:/extras/crafting-tweaks.json:ro
      - ./config:/config
    env_file: .env.secrets
    restart: unless-stopped
    tty: true
    stdin_open: true
#  backups:
#    image: 'itzg/mc-backup'
#    hostname: backups
#    container_name: backups
#    environment:
#        SRC_DIR: '/data'
#        RCON_HOST: minecraft
#        RCON_PORT: 25575
#        RCON_RETRIES: 10
#        RCON_RETRY_INTERVAL: 60s
#        BACKUP_NAME: 'peak'
#        RESTIC_ADDITIONAL_TAGS: 'minecraft server'
#        EXCLUDES: '*.jar,cache,bluemap,journeymap,libraries,.fabric,versions'
#        BACKUP_METHOD: restic
#        BACKUP_INTERVAL: 1d
#        PAUSE_IF_NO_PLAYERS: true
#        PRUNE_RESTIC_RETENTION: '--keep-daily 4 --keep-weekly 12'
#    volumes:
#      - ./minecraft:/data:ro
#      - ./backups:/backups
#    env_file: .env.secrets
#    depends_on:
#        - 'minecraft'
  website:
    image: 'ghcr.io/peaksmp/website:latest'
    hostname: website
    container_name: website
    init: true
    tty: true
    stdin_open: true
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
