services:
  minecraft:
    image: 'itzg/minecraft-server'
    hostname: minecraft
    container_name: minecraft
    cap_add:
      - "SYS_ADMIN"
    ports:
      - 25565:25565
      - 25575:25575
      - 8100:8100
    environment:
      EULA: true
      TYPE: 'QUILT'
      VERSION: '1.19'
      MEMORY: '10G'
      MAX_PLAYERS: 64
      LEVEL_TYPE: 'minecraft:normal'
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 8
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 100
      DIFFICULTY: 'hard'
      SPAWN_PROTECTION: 0
      SEED: '2527733443773253231'
      ENABLE_RCON: true
      SYNC_CHUNK_WRITES: false
      PREVIEW_CHAT: true
      ENFORCE_SECURE_PROFILE: true
      OVERRIDE_SERVER_PROPERTIES: true
      REMOVE_OLD_MODS: true
      REMOVE_OLD_VANILLATWEAKS: true
      MODS_FILE: '/extras/mods.txt'
      VANILLATWEAKS_FILE: '/extras/datapacks.json,/extras/crafting-tweaks.json'
      JVM_XX_OPTS: '-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:+DisableExplicitGC'
      JVM_DD_OPTS: '-Dfile.encoding=UTF-8'
    volumes:
      - ./minecraft:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./datapacks.json:/extras/datapacks.json:ro
      - ./crafting-tweaks.json:/extras/crafting-tweaks.json:ro
      - ./config:/config
    env_file: .env.secrets
    restart: unless-stopped
    tty: true
    stdin_open: true
  backup:
    image: 'itzg/mc-backup'
    hostname: backups
    container_name: backups
    environment:
        SRC_DIR: '/data'
        RCON_HOST: minecraft
        RCON_PORT: 25575
        RCON_RETRIES: 10
        RCON_RETRY_INTERVAL: 60s
        BACKUP_NAME: 'peak'
        RESTIC_ADDITIONAL_TAGS: 'minecraft server'
        EXCLUDES: '*.jar,cache,bluemap,libraries,.fabric,versions'
        BACKUP_METHOD: restic
        BACKUP_INTERVAL: 1d
        PAUSE_IF_NO_PLAYERS: true
        PRUNE_RESTIC_RETENTION: '--keep-daily 4 --keep-weekly 12'
    volumes:
      - ./minecraft:/data:ro
    env_file: .env.secrets
    depends_on:
        - 'minecraft'
  website:
    image: 'ghcr.io/peaksmp/website:latest'
    hostname: website
    container_name: website
    init: true
    tty: true
    stdin_open: true
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
