services:
  mc:
    image: 'itzg/minecraft-server'
    ports:
      - 25565:25565
      - 25575:25575
      - 8100:80
    environment:
      EULA: 'TRUE'
      TYPE: 'FABRIC'
      MEMORY: '2G'
      MAX_PLAYERS: '16'
      VIEW_DISTANCE: '12'
      MOTD: '\u00A7bPeak'
      DIFFICULTY: 'hard'
      ENABLE_RCON: 'true'
      ENABLE_COMMAND_BLOCK: 'true'
      USE_AIKAR_FLAGS: 'true'
      MAX_TICK_TIME: '-1'
      REMOVE_OLD_MODS: 'true'
      OVERRIDE_SERVER_PROPERTIES: 'true'
      MODS_FILE: '/extras/mods.txt'
    volumes:
      - ./minecraft:/data
      - ./mods.txt:/extras/mods.txt:ro
    tty: true
    stdin_open: true
