services:
  minecraft:
    image: 'itzg/minecraft-server'
    hostname: minecraft
    container_name: minecraft
    ports:
      - 25565:25565     # Minecraft
      - 25575:25575     # Rcon
      - 8100:8100       # Blue Map
      - 24454:24454/udp # Simple Voice Chat
    environment:
      EULA: true
      TYPE: 'FABRIC'
      VERSION: '1.21.7'
      MEMORY: '12G'
      MAX_PLAYERS: 64
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 8
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 150
      PAUSE_WHEN_EMPTY_SECONDS: 60
      DIFFICULTY: 'hard'
      SPAWN_PROTECTION: 0
      ENABLE_RCON: true
      SYNC_CHUNK_WRITES: false
      ENFORCE_SECURE_PROFILE: true
      OVERRIDE_SERVER_PROPERTIES: true
      REMOVE_OLD_VANILLATWEAKS: true
      SEED: "5435404126354230343"
      MOTD: "                             §b§lPeak\n                  §7§oChase the skies!" # Needs double quotes for '\n' to work
      ICON: 'https://github.com/peaksmp/server/blob/main/config/MiniMOTD/icons/peak.png?raw=true'
      MODS_FILE: '/extras/mods.txt'
      VANILLATWEAKS_FILE: '/extras/datapacks.json,/extras/crafting-tweaks.json'
      JVM_XX_OPTS: '-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:+DisableExplicitGC'
      JVM_DD_OPTS: '-Dfile.encoding=UTF-8'
    volumes:
      - ../data:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./datapacks.json:/extras/datapacks.json:ro
      - ./crafting-tweaks.json:/extras/crafting-tweaks.json:ro
      - ./config:/config
    env_file: .env.secrets
    restart: unless-stopped
  backups:
    image: 'itzg/mc-backup'
    hostname: backups
    container_name: backups
    environment:
        BACKUP_INTERVAL: 1d
        BACKUP_METHOD: restic
        BACKUP_NAME: 'peak'
        BACKUP_ON_STARTUP: false
        INITIAL_DELAY: 0
        PAUSE_IF_NO_PLAYERS: true
        SRC_DIR: '/data'
        RCON_HOST: minecraft
        RCON_PORT: 25575
        RESTIC_ADDITIONAL_TAGS: 'minecraft server'
        EXCLUDES: '*.jar,cache,bluemap,journeymap,libraries,.fabric,versions,DistantHorizons.sqlite,DistantHorizons.sqlite-shm,DistantHorizons.sqlite-wal,ledger.sqlite'
        PRUNE_RESTIC_RETENTION: '--keep-daily 4 --keep-weekly 12'
    volumes:
      - ../data:/data:ro
      - ../backups:/backups
    env_file: .env.secrets
    depends_on:
      minecraft:
        condition: service_healthy
  website:
    image: 'ghcr.io/peaksmp/website:latest'
    hostname: website
    container_name: website
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
