services:
  minecraft:
    image: 'itzg/minecraft-server'
    hostname: minecraft
    container_name: minecraft
    ports:
      - 25565:25565
      - 25575:25575
      - 8100:8100
    environment:
      EULA: true
      TYPE: 'FABRIC'
      VERSION: 'latest'
      MEMORY: '10G'
      MAX_PLAYERS: 64
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 8
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 150
      DIFFICULTY: 'hard'
      SPAWN_PROTECTION: 0
      SEED: 'peak'
      ENABLE_RCON: true
      SYNC_CHUNK_WRITES: false
      REMOVE_OLD_MODS: true
      REMOVE_OLD_DATAPACKS: true
      OVERRIDE_SERVER_PROPERTIES: true
      DATAPACKS_FILE: '/extras/datapacks.txt'
      MODS_FILE: '/extras/mods.txt'
      JVM_OPTS: '-server --add-modules jdk.incubator.vector'
      JVM_XX_OPTS: '-XX:+UseLargePages -XX:LargePageSizeInBytes=2M -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:+DisableExplicitGC'
      JVM_DD_OPTS: '-Dfile.encoding=UTF-8'
    volumes:
      - ./minecraft:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./datapacks.txt:/extras/datapacks.txt:ro
      - ./config:/config
      - /dev/hugepages:/dev/hugepages
    env_file: .env.secrets
    restart: unless-stopped
    tty: true
    stdin_open: true
  backup:
    image: 'itzg/mc-backup'
    hostname: backups
    container_name: backups
    environment:
        SRC_DIR: '/data'
        RCON_HOST: minecraft
        RCON_PORT: 25575
        RCON_RETRIES: 10
        RCON_RETRY_INTERVAL: 60s
        BACKUP_NAME: 'peak'
        RESTIC_ADDITIONAL_TAGS: 'minecraft server'
        EXCLUDES: '*.jar,cache,bluemap,libraries,.fabric,versions'
        BACKUP_METHOD: restic
        BACKUP_INTERVAL: 1d
        PAUSE_IF_NO_PLAYERS: true
        PRUNE_RESTIC_RETENTION: '--keep-daily 4 --keep-weekly 12'
    volumes:
      - ./minecraft:/data:ro
    env_file: .env.secrets
    depends_on:
        - 'minecraft'
  website:
    image: 'ghcr.io/peaksmp/website:latest'
    hostname: website
    container_name: website
    ports:
        - 3000:3000
    init: true
    tty: true
    stdin_open: true
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
