name: Deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts

      - name: Deploy to production
        uses: appleboy/ssh-action@v1
        env:
          REPOSITORY_URL: '${{ github.server_url }}/${{ github.repository }}'
          SERVER_ROOT: ${{ secrets.SERVER_ROOT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          envs: REPOSITORY_URL,SERVER_ROOT
          script_path: scripts/deploy.sh
